In [12]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# https://selenium-python.readthedocs.io/waits.html
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd
import os

path = "C:\Program Files (x86)\chromedriver"

driver = webdriver.Chrome(path)
driver.get("https://in.indeed.com/?from=gnav-jobsearch--jasx")


print(driver.title)

what = driver.find_element_by_id("text-input-what")
what.send_keys("data scientist")

where = driver.find_element_by_id("text-input-where")
where.send_keys("India")
where.send_keys(Keys.RETURN)

titles=[]
companies=[]
locations=[]
links =[]
reviews=[]
salaries = []

for i in range(1,5):
    

    # xpath syntax: //tagname[@attributeName='value'] (or) //tagname[contains(@attributeName, 'value')]

    job_card = driver.find_elements_by_xpath('//div[contains(@class,"clickcard")]')

    # print(job_card)

    for job in job_card:
       
    #  REVIEWS
        try:
            review = job.find_element_by_xpath('.//span[@class="ratingsContent"]').text
        except:
            review = "None"
        reviews.append(review)
   
    #   SALARY
        try:
            salary = job.find_element_by_xpath('.//span[@class="salaryText"]').text
        except:
            salary = "None"    
        salaries.append(salary)

    #   JOB LOCATION    
        try:
            location = job.find_element_by_xpath('.//span[contains(@class,"location")]').text
        except:
            location = "None"    
        locations.append(location)
        
    #   JOB TITLE        
        try:
            title  = job.find_element_by_xpath('.//h2[@class="title"]//a').text
        except:
            title = job.find_element_by_xpath('.//h2[@class="title"]//a').get_attribute(name="title")
        titles.append(title)
        
    #   APPLICATION LINK
        links.append(job.find_element_by_xpath('.//h2[@class="title"]//a').get_attribute(name="href"))
        
    #   COMPANY NAME    
        companies.append(job.find_element_by_xpath('.//span[@class="company"]').text)
        
    
    try:
        next_page = driver.find_element_by_xpath('//a[@aria-label={}]//span[@class="pn"]'.format(i+1))
        next_page.click()

    except:
        next_page = driver.find_element_by_xpath('//a[@aria-label="Next"]//span[@class="np"]')
        next_page.click()
         
    print("Page: {}".format(str(i+1)))

driver.quit()

pwd = os.getcwd()
#print(pwd)
master_dict = {"Job Title": titles, "Name of the Ompany": companies, "Location": locations, "Salary": salaries, "Review": reviews, "Link": links}
df = pd.DataFrame(master_dict)
print(df)
df.to_excel(pwd + "\Final_Output.xlsx", index=False)

Job Search India | Indeed
Page: 2
Page: 3
Page: 4
Page: 5
                                            Job Title  \
0                              Trainee data scientist
1                                      Data Scientist
2                                    Data Scientist I
3                                 Data Science Intern
4                                      Data Scientist
5                                       Data Engineer
6   Intern - Imaging Data Scientist (AI Applications)
7                               Senior Data Scientist
8                               Data Science Engineer
9                                      Data Scientist
10                                     Data Scientist
11                       Data Scientist - Plotly Dash
12                                     Data Scientist
13                           Associate Data Scientist
14                                     Data Scientist
15          Machine Learning and Data Science Trainer
16
17
18
19
20
21
22
23
24
25
26
27
28
29                Data Scientist - Campaign Analytics
30                                Data Science Intern
31             Lead Data Scientist - Machine Learning
32                                   Data Scientist I
33                                     Data Scientist
34                                     Data Scientist
35           Associate Data Scientist - Space Planner
36             Data Scientist - Apache Spark - Python
37                                Data Science Intern
38                   Data Science Analysis Internship
39                                     Data Scientist
40                              Senior Data Scientist
41                                     Data Scientist
42                                     Data Scientist
43                                     Data Scientist
44                                     Data Scientist
45                           Data Scientist / Analyst
46                                     Data Scientist
47                       Data Scientist - Innovations
48                    Data Scientist & python Trainer
49     Data Analytics & Data Visualization Internship
50                            Data Science Consultant
51                                     Data Scientist
52                                     Data Scientist
53                                     Data Scientist
54                              Senior Data Scientist
55                  Data Scientist / Machine Learning
56                                     Data Scientist
57                                     Data Scientist
58                              Expert Data Scientist
59                                     Data Scientist

                       Name of the Ompany                        Location  \
0                       Business pointers             Mumbai, Maharashtra
1                                  7owdin               Jalandhar, Punjab
2                               Honeywell            Bengaluru, Karnataka
3                                 Asquero                    Delhi, Delhi
4                                Rinteger            Bengaluru, Karnataka
5                                Ohmyhome                    Delhi, Delhi
6                                   Intel            Bengaluru, Karnataka
7                   WebShar India Pvt Ltd               Pune, Maharashtra
8                                  Mystro             Mumbai, Maharashtra
9                                   Adobe            Noida, Uttar Pradesh
10                         Eton Solutions            Bengaluru, Karnataka
11                  loyalytics consulting            Bengaluru, Karnataka
12            Canopus Infosystems PVT LTD          Indore, Madhya Pradesh
13       Alpha Analytics Services Pvt Ltd               Pune, Maharashtra
14                    OM Software Pvt Ltd               Pune, Maharashtra
15                          Aedifico Tech                            None
16                                                                   None
17                                                                   None
18
19
20
21
22
23
24
25
26
27
28
29                  loyalytics consulting            Bengaluru, Karnataka
30              Feednet Solutions Pvt Ltd  Madhapur, Hyderabad, Telangana
31                    Gramener Technology            Hyderabad, Telangana
32                            Caterpillar            Bengaluru, Karnataka
33                                   Zeta            Bengaluru, Karnataka
34                 Applied Materials Inc.            Bengaluru, Karnataka
35                                  Shell             Chennai, Tamil Nadu
36          Smart Machines and Structures                        Goa, Goa
37      Proton Expert Systems & Solutions            Bengaluru, Karnataka
38         Occipital Labs Private Limited                    Delhi, Delhi
39                          XPO Logistics             Mumbai, Maharashtra
40              JPMorgan Chase Bank, N.A.            Bengaluru, Karnataka
41              RTEX HR Services Pvt. Ltd            Bengaluru, Karnataka
42                      iGloble Solutions             Kalkaji Devi, Delhi
43                                WishFin            Noida, Uttar Pradesh
44                        Aptus Data LAbs            Bengaluru, Karnataka
45                               GlowRoad            Bengaluru, Karnataka
46                                   Yara            Bengaluru, Karnataka
47                         Merkle Sokrati               Pune, Maharashtra
48      Try Logic Soft Solutions Pvt Ltd.      Vijayawada, Andhra Pradesh
49          iTech Mission Private Limited                    Delhi, Delhi
50                          Ramco Systems                           India
51          Flexiventures Private Limited    Andheri, Mumbai, Maharashtra
52                                  Bayer            Bengaluru, Karnataka
53                    FedEx Express MEISA     Guindy, Chennai, Tamil Nadu
54  TALRIGHT TECHNOLOGIES PRIVATE LIMITED            Bengaluru, Karnataka
55        ANI Calls India Private Limited            Noida, Uttar Pradesh
56                Boston Consulting Group                New Delhi, Delhi
57                              XCEEDANCE                Gurgaon, Haryana
58                                     HP                            None
59                             ESRI, Inc.                New Delhi, Delhi

                            Salary Review  \
0    ₹6,00,000 - ₹12,00,000 a year   None
1        ₹34,600 - ₹76,000 a month   None
2                             None    3.7
3         ₹8,265 - ₹22,753 a month   None
4        ₹10,000 - ₹25,000 a month   None
5    ₹1,50,000 - ₹3,00,000 a month   None
6                             None    4.1
7                ₹15,00,000 a year   None
8                  ₹40,000 a month   None
9                             None    4.3
10                            None   None
11   ₹8,00,000 - ₹15,00,000 a year   None
12       ₹15,000 - ₹55,000 a month   None
13    ₹4,20,000 - ₹5,40,000 a year   None
14   ₹2,50,000 - ₹5,00,000 a month   None
15       ₹20,000 - ₹50,000 a month   None
16                            None
17                                   None
18                                   None
19                                   None
20                            None
21                            None
22                                   None
23                                   None
24                            None
25                            None
26                            None
27                            None   None
28                            None
29  ₹10,00,000 - ₹15,00,000 a year   None
30        ₹8,000 - ₹15,000 a month   None
31                            None    4.5
32                            None    3.9
33                            None    3.9
34                            None    3.9
35                            None    3.9
36     ₹25,000 - ₹1,00,000 a month   None
37        ₹8,938 - ₹16,599 a month   None
38                 ₹10,000 a month   None
39                            None    3.2
40                            None    3.9
41       ₹35,000 - ₹60,000 a month   None
42                            None   None
43                            None    3.7
44                            None    3.0
45                ₹7,00,000 a year    4.3
46                            None    4.3
47                            None    3.8
48                            None   None
49                 ₹10,000 a month   None
50                            None    3.7
51                            None   None
52                            None    4.2
53                            None   None
54  ₹25,00,000 - ₹30,00,000 a year   None
55   ₹9,00,000 - ₹16,00,000 a year   None
56                            None    4.2
57                            None    3.3
58                            None    4.0
59                            None    3.8

                                                 Link
0   https://in.indeed.com/company/Business-pointer...
1   https://in.indeed.com/company/7owdin-pvt-ltd/j...
2   https://in.indeed.com/rc/clk?jk=4cd015a9024788...
3   https://in.indeed.com/company/Asquero/jobs/Dat...
4   https://in.indeed.com/company/Rinteger/jobs/Da...
5   https://in.indeed.com/company/Ohmyhome/jobs/Da...
6   https://in.indeed.com/rc/clk?jk=4f1662f4a73e86...
7   https://in.indeed.com/company/WebShar-India-Pv...
8   https://in.indeed.com/company/Mystro/jobs/Data...
9   https://in.indeed.com/rc/clk?jk=4c7fec5becef6d...
10  https://in.indeed.com/rc/clk?jk=5c50d6c37fce34...
11  https://in.indeed.com/rc/clk?jk=be2eaee4cd0716...
12  https://in.indeed.com/company/Canopus-Infosyst...
13  https://in.indeed.com/company/Alpha-Analytics-...
14  https://in.indeed.com/company/OM-Software-Pvt....
15  https://in.indeed.com/pagead/clk?mo=r&ad=-6NYl...
16  https://in.indeed.com/pagead/clk?mo=r&ad=-6NYl...
17  https://in.indeed.com/pagead/clk?mo=r&ad=-6NYl...
18  https://in.indeed.com/company/Uplatz/jobs/Data...
19  https://in.indeed.com/rc/clk?jk=05f72fc2edc553...
20  https://in.indeed.com/rc/clk?jk=9580d2e2cabc28...
21  https://in.indeed.com/rc/clk?jk=69041975cabdee...
22  https://in.indeed.com/company/Kaplan-India/job...
23  https://in.indeed.com/company/SVND-Technologie...
24  https://in.indeed.com/rc/clk?jk=7164d95a04777c...
25  https://in.indeed.com/rc/clk?jk=44bf28bfeb300c...
26  https://in.indeed.com/rc/clk?jk=44d4c42143f324...
27  https://in.indeed.com/company/Expertia-Incorpo...
28  https://in.indeed.com/rc/clk?jk=7ad3c833c175e3...
29  https://in.indeed.com/rc/clk?jk=cb1a8d13521cdc...
30  https://in.indeed.com/company/Feednet-Solution...
31  https://in.indeed.com/company/Gramener-Technol...
32  https://in.indeed.com/rc/clk?jk=db3fbdee5f5257...
33  https://in.indeed.com/rc/clk?jk=82d4457446cdc6...
34  https://in.indeed.com/rc/clk?jk=1de4a4b01b5160...
35  https://in.indeed.com/rc/clk?jk=455e127770da5b...
36  https://in.indeed.com/company/Smart-Machines-a...
37  https://in.indeed.com/company/Proton-Expert-Sy...
38  https://in.indeed.com/rc/clk?jk=0951f5de4d7041...
39  https://in.indeed.com/rc/clk?jk=7456ae57f0a8e5...
40  https://in.indeed.com/rc/clk?jk=31a6172456f610...
41  https://in.indeed.com/company/RTEX-HR-Services...
42  https://in.indeed.com/rc/clk?jk=254483a2a7f91f...
43  https://in.indeed.com/rc/clk?jk=83f3ba54497948...
44  https://in.indeed.com/rc/clk?jk=193adf787a627e...
45  https://in.indeed.com/company/GlowRoad/jobs/Da...
46  https://in.indeed.com/rc/clk?jk=4b3cdf56cea64c...
47  https://in.indeed.com/rc/clk?jk=e0428e0ee4a8db...
48  https://in.indeed.com/company/Try-Logic-Soft-S...
49  https://in.indeed.com/rc/clk?jk=c3f2713db9a99d...
50  https://in.indeed.com/rc/clk?jk=81108186329920...
51  https://in.indeed.com/rc/clk?jk=c471eb86057734...
52  https://in.indeed.com/rc/clk?jk=19cd430c221ccf...
53  https://in.indeed.com/rc/clk?jk=b29a3d4edff76f...
54  https://in.indeed.com/company/TALRIGHT-TECHNOL...
55  https://in.indeed.com/rc/clk?jk=2966be22f7a5f8...
56  https://in.indeed.com/rc/clk?jk=414ab6100154e9...
57  https://in.indeed.com/rc/clk?jk=1455d196020017...
58  https://in.indeed.com/pagead/clk?mo=r&ad=-6NYl...
59  https://in.indeed.com/rc/clk?jk=11c37f88790cd2...